#!/usr/bin/env bash

readonly API_URL='https://disease.sh/v3/covid-19'

# deixando claro que data é um array associativo
declare -A data

json2array() {
  local jsonData="$1"

  # verificando se é um JSON válido
  jq empty <<<"$jsonData" 2>/dev/null || return 1

  while IFS== read -r key value; do
    data[$key]="$value"
  done < <(jq -r '. | to_entries | .[] | .key + "=" + (.value|tostring)' <<<"$jsonData")
}

main() {
  local json
  
  # primeiro dados globais:
  json="$(curl --silent "${API_URL}/all")"

  if ! json2array "$json"; then
    echo "ERRO: falha ao obter os dados de $API_URL" >&2
    exit 1
  fi

  echo -n "
------Dados Globais🌐------
┌──────────────────┐
│➤Número de casos: ${data[cases]}
│➤Número de mortes: ${data[deaths]}
│➤Pacientes curados: ${data[recovered]}
└──────────────────┘
"
}

main "$@"
